# Kernel services BC layer
services:
    ezpublish.fieldType.ezrichtext:
        alias: EzSystems\EzPlatformRichText\eZ\FieldType\RichText\Type

    ezpublish.fieldType.ezrichtext.externalStorage:
        alias: EzSystems\EzPlatformRichText\eZ\FieldType\RichText\RichTextStorage

    ezpublish.fieldType.ezrichtext.converter:
        alias: EzSystems\EzPlatformRichText\eZ\Persistence\Legacy\RichTextFieldValueConverter

    ezpublish.fieldType.indexable.ezrichtext:
        alias: EzSystems\EzPlatformRichText\eZ\FieldType\RichText\SearchField

    ezpublish_rest.field_type_processor.ezrichtext:
        alias: EzSystems\EzPlatformRichText\eZ\REST\FieldTypeProcessor\RichTextProcessor

    EzSystems\RepositoryForms\FieldType\Mapper\RichTextFormMapper:
        alias: EzSystems\EzPlatformRichText\Form\Mapper\RichTextFormMapper

    ezpublish.fieldType.ezrichtext.converter.input.dispatcher:
        alias: ezrichtext.converter.input.dispatcher

    ezpublish.fieldType.ezrichtext.validator.docbook:
        alias: ezrichtext.validator.docbook

    ezpublish.fieldType.ezrichtext.validator.input.dispatcher:
        alias: ezrichtext.validator.input.dispatcher

    ezpublish.fieldType.ezrichtext.validator.internal_link:
        alias: ezrichtext.validator.internal_link

    ezpublish.fieldType.ezrichtext.normalizer.input:
        alias: ezrichtext.normalizer.input

    eZ\Publish\Core\FieldType\RichText\CustomTagsValidator:
        alias: EzSystems\EzPlatformRichText\eZ\RichText\Validator\CustomTagsValidator

    ezpublish.fieldType.ezrichtext.converter.input.xhtml5.core:
        alias: ezrichtext.converter.input.xhtml5.core

    ezpublish.fieldType.ezrichtext.converter.input.xhtml5.programlisting:
        alias: ezrichtext.converter.input.xhtml5.programlisting

    ezpublish.fieldType.ezrichtext.converter.input.xhtml5:
        alias: ezrichtext.converter.input.xhtml5

    ezpublish.fieldType.ezrichtext.converter.link:
        alias: ezrichtext.converter.link

    ezpublish.fieldType.ezrichtext.renderer:
        alias: ezrichtext.renderer

    ezpublish.fieldType.ezrichtext.converter.template:
        alias: ezrichtext.converter.template

    ezpublish.fieldType.ezrichtext.converter.embed:
        alias: ezrichtext.converter.embed

    ezpublish.fieldType.ezrichtext.converter.output.xhtml5.core:
        alias: ezrichtext.converter.output.xhtml5.core

    ezpublish.fieldType.ezrichtext.converter.output.xhtml5.fragment:
        alias: ezrichtext.converter.output.xhtml5.fragment

    ezpublish.fieldType.ezrichtext.converter.output.xhtml5:
        alias: ezrichtext.converter.output.xhtml5

    ezpublish.fieldType.ezrichtext.converter.edit.xhtml5:
        alias: ezrichtext.converter.edit.xhtml5

    ezpublish.fieldType.ezrichtext.validator.output.ezxhtml5:
        alias: ezrichtext.validator.output.ezxhtml5
