dist: trusty
language: php

services:
  - mysql

# Mysql isn't installed on trusty (only client is), so we need to specifically install it
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

cache:
  directories:
    - $HOME/.composer/cache/files

branches:
  only:
    - master
    - /^\d.\d+$/

matrix:
  fast_finish: true
  include:
# 7.3
    - name: '[PHP 7.3] Solr Search Engine Integration'
      php: 7.3
      env:
        - SOLR_VERSION="7.7.3"
        - TEST_CONFIG="phpunit-integration-legacy-solr.xml"
        - CORES_SETUP="shared"
        - SOLR_CONFIG="vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/schema.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/custom-fields-types.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/language-fieldtypes.xml"
    - name: '[PHP 7.3] AdminUI Behat tests'
      php: 7.3
      env:
        - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/selenium.yml"
        - BEHAT_OPTS="--profile=browser --suite=admin-ui --tags=@richtext -c=behat_ibexa_oss.yaml"
        - APP_ENV=behat
        - APP_DEBUG=1
        - PROJECT_VERSION=^3.3.x-dev

# reduce depth (history) of git checkout
git:
  depth: 30

# disable mail notifications
notifications:
  email: false
  slack:
    rooms:
      - secure: "KjjHNUh2GU9OkIhvppS1S6SALGwDa4p8rdYO6mxg4hcKB2CnygPV15fAKTRexgy1q1xZI2ts+fPQynqImp34KvtgRFfkea89UebbLEEOrwvaDQJ+3xv+oXPsFOl3jB0dftSAEO7I0K2OOp40rBRmk5Q3Srr34MZcRZEo5D2Kdu0AvYiAE/nhA07tJkTApTmuWfMa8yUxLCMocOACBe2OvNqEvbv/D0tt4tLPHDqnFvAvCZQFaaoKhOzZFc83NiM281N8xtP3E8rmImY1nKORl13owDQ5i5Fz/5Pn20ttBtUDYTJwUQ9wsaT8RStgL8w+YFYtKVMaBBtP2BIWoz7R278pr8q49HeTx72FIlWDsTknKXjfqzpqwfrPhoJUwB1XmQcXoi1z0z8bvGL3GPgpnYrENxmuUX/CYnL0dq9jkI9twxNr/P+5JClb/J+JZEKta8f1bZUdq7zPRPL5+hrDlg6elvwLkSAXA5zh0/tVd1WKWgmL7eEjqTi1ew3RIVcflsJNHNGZBXD9jpbuXLDa7QaTlwqHBHdERAExNnlDse9U0p6yJLFS2oCqBTVHvleX3xkclPSvaJSlUFtn7zNR+JpUPNbN17ADaYf3Wzo2xifrMjbv7POEotL3ddlkuCAbwAJo4hMJwcQD1vahk28AOivyoAMIXlcOZ2oKCxqWE8Y="
    on_success: change
    on_failure: always
    on_pull_requests: false

# setup requirements for running unit/integration/behat tests
before_install:
  # Disable xdebug to speed things up as we don't currently generate coverage on travis
  - phpenv config-rm xdebug.ini
  # Add custom php.ini configuration for test matrix
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "default_charset=UTF-8" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Detecting timezone issues by testing on random timezone
  - TEST_TIMEZONES=("America/New_York" "Asia/Calcutta" "UTC")
  - TEST_TIMEZONE=${TEST_TIMEZONES["`shuf -i 0-2 -n 1`"]}

install:
  # Prepare system
  - if [ "${TEST_CONFIG}" != "" ] ; then ./bin/.travis/prepare_unittest.sh; fi
  - travis_retry composer install --no-progress --no-interaction --prefer-dist --no-suggest
  # Setup Solr / Elastic search if asked for
  - if [ "${TEST_CONFIG}" = "phpunit-integration-legacy-solr.xml" ] ; then ./vendor/ezsystems/ezplatform-solr-search-engine/bin/.travis/init_solr.sh; fi
  # Prepare Behat environment if needed
  - if [ "${BEHAT_OPTS}" != "" ]; then ./vendor/bin/prepare_project_edition.sh oss ${PROJECT_VERSION} ${COMPOSE_FILE} ; fi

# execute phpunit or behat as the script command
script:
  - if [ "${TEST_CONFIG}" != "" ] ; then php -d date.timezone=$TEST_TIMEZONE ./vendor/bin/phpunit -c $TEST_CONFIG ; fi
  - if [ "${BEHAT_OPTS}" != "" ]; then cd "$HOME/build/project"; docker-compose exec --user www-data app sh -c "./vendor/bin/ezbehat $BEHAT_OPTS" ; fi

after_failure:
  # Will show us the last bit of the log of container's main processes
  # (not counting shell process above running php and behat)
  # NOTE: errors during docker setup of travis build won't show up here (can't output all as it is too much in debug/verbose mode)
  - docker-compose logs -t --tail=15
  # Will show us what is up, and how long it's been up
  - docker ps -s
after_script:
  - if [ "${BEHAT_OPTS}" != "" ] ; then vendor/bin/ezreport ; fi
