services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformRichTextBundle\Templating\Twig\Extension\RichTextConverterExtension:
        arguments:
            $richTextOutputConverter: '@ezrichtext.converter.output.xhtml5'
            $richTextEditConverter: '@ezrichtext.converter.edit.xhtml5'

    EzSystems\EzPlatformRichTextBundle\Templating\Twig\Extension\YoutubeIdExtractorExtension: ~
